<h1 style="color:lightblue;"><center><b>Numpy (Numerical Python)</b></center></h1>

## Why Numpy?


NumPy is a powerful numerical computing library in Python. It provides support for arrays, matrices, and many mathematical functions to operate on these data structures. Here are some reasons why we use NumPy:

1. **Performance**: NumPy is implemented in C/C++, which makes it much faster than standard Python lists for numerical operations.
2. **Array Operations**: It provides a wide range of array operations that are both efficient and convenient.
3. **Mathematical Functions**: NumPy includes a large number of mathematical functions, such as linear algebra, statistical operations, and more.
4. **Integration**: It integrates well with other scientific computing libraries like SciPy, Pandas, and Matplotlib.
5. **Memory Efficiency**: NumPy arrays are more memory-efficient than Python lists, especially for large datasets.

Overall, NumPy is an essential library for scientific computing and data analysis in Python.

In [4]:
## How to import numpy and check the version of numpy
## NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.
## NumPy is developed by a large community of people. You can find more information about NumPy in the official website of NumPy.

import numpy as np 

np.__version__


'1.26.4'

In [5]:
## Numpy use array to store data. The array is a data structure that stores values of same data type.
## The array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type.

py_list = [1, 2, 3, 4, 5]

np_array = np.array([1, 2, 3, 4, 5])
## or
np_array = np.array(py_list)

print(type(py_list))
print(type(np_array))

<class 'list'>
<class 'numpy.ndarray'>


In [6]:
## What is numpy.ndarray?
## It define the dimensions of the array (1D, 2D, 3D, etc.) and some basic attributes of the array like its shape, size, data type, etc.

print(np_array.ndim) ## ndim is used to check the dimension of the array. 1
print(np_array.shape) ## shape is used to check the shape of the array. (5,)
print(np_array.size) ## size is used to check the size of the array. 5
## The size of the array is equal to the total number of elements in the array.

1
(5,)
5


In [7]:
## let varify that the data inside the array is of same data type

l = [1, 2, 3, 4, 5, "string_value"]
arr = np.array(l)
print(l)
print(arr)
## We can see that the array has converted all the elements of the list to string. This is one of the main advantages of using numpy with python. It automatically converts the data to the same data type.
## While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type.

[1, 2, 3, 4, 5, 'string_value']
['1' '2' '3' '4' '5' 'string_value']


In [9]:
## Numpy matrix
## A matrix is a two-dimensional data structure where numbers are arranged into rows and columns. 
## For example, a matrix of the form 3x3 has 3 rows and 3 columns.

l = [1,2,3,4,5]

print(np.array(l))
print(np.matrix(l))

## we can see the difference between the array and matrix.
## The array is a data structure that stores values of same data type.
## The matrix is a data structure that stores values of the same data type and has two dimensions.


[1 2 3 4 5]
[[1 2 3 4 5]]


In [10]:
## Note that numpy matrices are strictly 2-dimensional, while numpy arrays (ndarrays) are N-dimensional.

np.matrix([[[1, 2], [3, 4]]]) ## ValueError: matrix must be 2-dimensional

ValueError: matrix must be 2-dimensional

In [11]:
## np.array()
## np.asarray()
## np.asanyarray()
l = [[1, 2, 3], [4, 5, 6]]

## np.array() is used to create an array from a list or tuple.
np.array(l)

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
## np.asarray() is used to convert input to an array.
np.asarray(l)

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
## np.asanyarray() is used to convert input to an array if input is not already an array.
np.asanyarray(l)

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
## np.array() vs np.asarray()
## The main difference between np.array() and np.asarray() is that np.array() is used to create an array from a list or tuple while np.asarray() is used to convert input to an array.

## np.array() vs np.asanyarray()
## The main difference between np.array() and np.asanyarray() is that np.array() is used to create an array from a list or tuple while np.asanyarray() is used to convert input to an array if input is not already an array.

In [15]:
mat = np.matrix([[1, 2, 3], [4, 5, 6]])
mat

matrix([[1, 2, 3],
        [4, 5, 6]])

In [16]:
np.asanyarray(mat)
# The asanyarray() function is used to convert input to an array if input is not already an array.
# If input is an ndarray it is returned unaltered. 
# If input is a tuple, a list, or an ndarray, a new array is created with input as the first array in the new array. 
# If input is a subclass of ndarray, a base class ndarray is returned.

matrix([[1, 2, 3],
        [4, 5, 6]])

## Different ways to create arrays

In [ ]:
## By using np.fromfunction() function

## The np.fromfunction() function is used to construct an array by executing a function over each coordinate.

arr = np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)
arr

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [19]:
## By using np.fromiter() function
## The np.fromiter() function is used to create a new 1-dimensional array from an iterable object.

iterable = (x*x for x in range(5))
arr = np.fromiter(iterable, int)
arr

array([ 0,  1,  4,  9, 16])

In [20]:
## by using np.fromstring() function
## The np.fromstring() function is used to create a new 1-dimensional array from a string.

arr = np.fromstring('234 234', sep=' ')
arr

array([234., 234.])

In [ ]:
## by using np.arange() function
## The np.arange() function is used to create an array with evenly spaced values within a given interval.
arr = np.arange(0.1, 10.0, 0.2 )
arr

array([0.1, 0.3, 0.5, 0.7, 0.9, 1.1, 1.3, 1.5, 1.7, 1.9, 2.1, 2.3, 2.5,
       2.7, 2.9, 3.1, 3.3, 3.5, 3.7, 3.9, 4.1, 4.3, 4.5, 4.7, 4.9, 5.1,
       5.3, 5.5, 5.7, 5.9, 6.1, 6.3, 6.5, 6.7, 6.9, 7.1, 7.3, 7.5, 7.7,
       7.9, 8.1, 8.3, 8.5, 8.7, 8.9, 9.1, 9.3, 9.5, 9.7, 9.9])

In [ ]:

arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

 ## Limitations of range() function over np.arange() function
* The range() function is used to generate a sequence of numbers. It is used inside the for loop to generate numbers in the sequence.
* The np.arange() function is used to create an array with evenly spaced values within a given interval.
* range() function only work with int while np.arange() can be used to generate int and float both.

In [31]:
## By using np.linespace() function
## The np.linspace() function is used to create an array of evenly spaced values over a specified interval.

arr = np.linspace(0, 10, 50)
arr

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [33]:
## By using np.logspace() function
## The np.logspace() function is used to create an array of evenly spaced values over a specified interval on a log scale.  

arr = np.logspace(0, 10, 20, 2)
arr

array([1.00000000e+00, 3.35981829e+00, 1.12883789e+01, 3.79269019e+01,
       1.27427499e+02, 4.28133240e+02, 1.43844989e+03, 4.83293024e+03,
       1.62377674e+04, 5.45559478e+04, 1.83298071e+05, 6.15848211e+05,
       2.06913808e+06, 6.95192796e+06, 2.33572147e+07, 7.84759970e+07,
       2.63665090e+08, 8.85866790e+08, 2.97635144e+09, 1.00000000e+10])